appveyor:
  image: Visual Studio 2017
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider:
  osx: circle
shippable:
  projectId: 5cc26d6eb42e400007b7583a
  secure:
    BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==
travis:
  secure:
    BINSTAR_TOKEN: JZwVDH5KwSyByzTRGbXzL6VEXx5Bsa942Rr0RHjvQ2kDhpxWx+g3uM+Z+46pZb162AbFX+fH28zZwMtLuIMhcBVOac+HT+1nJ90sXF4/h/J59OBshhThiwVx9nKQJ4/S5OlpM/UzTZfxEAOHLCpN8KVSGhdcj51UW2pNFcWFCOYM4xwXEwl1SZBrBZ6nl2nVIS33iF+lfcWv8g5ew2srtQY0N3+LL58sU2MPf/SBQiE72zUc8W9dzn3iJwA9Zn8w1PBIZWMXFK1Z+mJJl83rQwJ04aSSEqZsuPcs0vOTodr2CN7lM6Jx4ffI5s4qbsA2HPe5XrTZyVyQkEKzU5kehgMmUKQK5xHsE1ePMoR7oRINLLpDWVK8Z9rpjl7eJsb9XOtCQY8fEN64T7yybOKXEGUcOdcQuOh65ybS5HF1tiKwe9R2ULiqe9T/W8eNkq+B43yk7k7zOalc3PP3ZDWxrvZ6qHiugxVQ4rsTomBCAlpXJ2aw+uVafc/fSQgyqLzrstUjrLwmYK3nWCxB3O3iPArBY7cYzM/JJNguqCGYrF13LBZCnU5BggwVcg3grrLqzuraKlqGnLT/Uw8vBV03Gge4OzM8xTb03WCS46xOGYZI3QBG/lIvUtA/Wk5A2BmpaESQa2vfOYvvEudnzl22Oufu22QUCi1DyG1l8jf3s6A=
